# Generated by Django 4.1.5 on 2023-01-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stbd_code',
            field=models.CharField(max_length=16, verbose_name='STBD_CODE'),
        ),
    ]
